#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir//bin/bash" ]; then
  "$basedir//bin/bash"  "$basedir/node_modules/node-red/bin/node-red-pi" "$@"
  ret=$?
else 
  /bin/bash  "$basedir/node_modules/node-red/bin/node-red-pi" "$@"
  ret=$?
fi
exit $ret
